CREATE TABLE `rede_import_files` (
	`id` int AUTO_INCREMENT NOT NULL,
	`fileName` varchar(255) NOT NULL,
	`fileUrl` text NOT NULL,
	`periodStart` date NOT NULL,
	`periodEnd` date NOT NULL,
	`totalRecords` int NOT NULL,
	`totalValue` decimal(15,2) NOT NULL,
	`importedBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `rede_import_files_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `rede_inove_reconciliation` (
	`id` int AUTO_INCREMENT NOT NULL,
	`redeSaleId` int NOT NULL,
	`redeDate` date NOT NULL,
	`redeValue` decimal(10,2) NOT NULL,
	`redeModalidade` varchar(50),
	`redeBandeira` varchar(50),
	`inoveSaleId` int,
	`inoveDate` date,
	`inoveValue` decimal(10,2),
	`status` enum('matched','unmatched_rede','unmatched_inove','divergent') NOT NULL,
	`divergenceReason` varchar(255),
	`divergenceAmount` decimal(10,2),
	`bankStatementId` int,
	`bankCreditDate` date,
	`bankCreditValue` decimal(10,2),
	`reconciliationDate` date NOT NULL,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `rede_inove_reconciliation_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `rede_sales_import` (
	`id` int AUTO_INCREMENT NOT NULL,
	`dataDaVenda` date NOT NULL,
	`horaDaVenda` varchar(20),
	`statusDaVenda` varchar(50) NOT NULL,
	`valorDaVendaOriginal` decimal(10,2) NOT NULL,
	`valorDaVendaAtualizado` decimal(10,2),
	`modalidade` varchar(50) NOT NULL,
	`tipo` varchar(100),
	`bandeira` varchar(50),
	`numeroDeParcelas` int,
	`taxaMDR` decimal(5,2),
	`valorMDR` decimal(10,2),
	`taxaRecebimentoAutomatico` decimal(5,2),
	`valorTaxaRecebimentoAutomatico` decimal(10,2),
	`valorTotalTaxas` decimal(10,2),
	`valorLiquido` decimal(10,2),
	`nsuCV` varchar(50) NOT NULL,
	`idTransacao` varchar(100),
	`numeroAutorizacao` varchar(50),
	`prazoDeRecebimento` varchar(50),
	`numeroDoEstabelecimento` varchar(50) NOT NULL,
	`nomeDoEstabelecimento` varchar(200),
	`cnpj` varchar(20),
	`numeroDoCartao` varchar(50),
	`codigoDaMaquininha` varchar(50),
	`tipoDeMaquininha` varchar(50),
	`canceladaPeloEstabelecimento` boolean DEFAULT false,
	`dataDoCancelamento` date,
	`valorCancelado` decimal(10,2),
	`emDisputaDeChargeback` boolean DEFAULT false,
	`dataQueEntrouEmDisputaDeChargeback` date,
	`resolucaoDoChargeback` varchar(100),
	`importFileId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `rede_sales_import_id` PRIMARY KEY(`id`)
);
