CREATE TABLE `purchase_invoice_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`invoiceId` int NOT NULL,
	`lineNumber` int NOT NULL,
	`supplierCode` varchar(100),
	`description` varchar(500) NOT NULL,
	`category` varchar(50) NOT NULL DEFAULT 'insumos',
	`quantity` decimal(14,3) NOT NULL,
	`unit` varchar(20) NOT NULL DEFAULT 'UN',
	`unitPrice` decimal(14,4) NOT NULL,
	`totalPrice` decimal(14,2) NOT NULL,
	`confidence` decimal(5,4),
	`productId` int,
	`operationalItemId` int,
	`boxStockId` int,
	`linkStatus` enum('pending','linked','ignored') NOT NULL DEFAULT 'pending',
	`rawData` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `purchase_invoice_items_id` PRIMARY KEY(`id`),
	CONSTRAINT `purchase_invoice_line_idx` UNIQUE(`invoiceId`,`lineNumber`)
);
--> statement-breakpoint
CREATE TABLE `purchase_invoices` (
	`id` int AUTO_INCREMENT NOT NULL,
	`source` enum('pdf','xml') NOT NULL DEFAULT 'pdf',
	`fileName` varchar(255) NOT NULL,
	`fileKey` varchar(500) NOT NULL,
	`fileUrl` varchar(1000) NOT NULL,
	`fileHash` varchar(64) NOT NULL,
	`fileSize` int NOT NULL,
	`status` enum('pending','processing','extracted','review_required','confirmed','error') NOT NULL DEFAULT 'pending',
	`supplierName` varchar(255),
	`supplierCnpj` varchar(20),
	`operationalSupplierId` int,
	`invoiceNumber` varchar(30),
	`accessKey` varchar(44),
	`issueDate` varchar(10),
	`totalAmount` decimal(14,2),
	`itemSubtotal` decimal(14,2),
	`totalItems` int NOT NULL DEFAULT 0,
	`confidence` decimal(5,4),
	`model` varchar(100),
	`promptTokens` int,
	`completionTokens` int,
	`durationMs` int,
	`validationErrors` json,
	`errorMessage` text,
	`uploadedBy` int NOT NULL,
	`reviewedBy` int,
	`processedAt` timestamp,
	`confirmedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `purchase_invoices_id` PRIMARY KEY(`id`),
	CONSTRAINT `purchase_invoices_fileHash_unique` UNIQUE(`fileHash`)
);
